# Generated by Django 5.0.2 on 2025-03-04 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_shop_remove_product_gearbox_remove_product_recommend_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_telegram',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_vk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_entrance',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_flat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_floor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_house',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_intercom',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_region',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager_has_been_notified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pick-up_point', 'Пункт выдачи '), ('by_courier', 'Курьером')], default='pick-up_point', max_length=150, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('in_assembly', 'В сборке'), ('transferred_to_delivery', 'Передаётся в доставку'), ('on_the_way', 'В пути'), ('awaiting_receipt', 'Ожидает получения'), ('received', 'Получен '), ('canceled', 'Отменен')], default='awaiting_payment', max_length=150, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=150, verbose_name='Область')),
                ('city', models.CharField(max_length=150, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Квартира')),
                ('entrance', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Домофон')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shippingaddress', verbose_name='Адрес доставки'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='cart_order_created_27f3c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='amount_gte_0'),
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quantity_gte_0'),
        ),
    ]
