# Generated by Django 5.0.2 on 2025-03-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_deliveryorder_customer_alter_order_options_and_more'),
        ('products', '0002_shop_remove_product_gearbox_remove_product_recommend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
