# Generated by Django 5.0.2 on 2025-03-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_payment_id'),
        ('products', '0002_shop_remove_product_gearbox_remove_product_recommend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='С')),
                ('end_date', models.DateField(verbose_name='По')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка')),
                ('category_performance', models.JSONField(blank=True, help_text='Словарь с ID категории и объемами продаж', null=True, verbose_name='Продажи по категориям')),
                ('products_performance', models.JSONField(blank=True, help_text='Словарь с ID товаров и объемами продаж', null=True, verbose_name='Продажи по товарам')),
                ('orders', models.ManyToManyField(blank=True, null=True, related_name='store_sales_reports', to='cart.order', verbose_name='Заказы')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_sales_reports', to='products.shop', verbose_name='Магазин')),
            ],
        ),
    ]
