# Generated by Django 5.0.2 on 2025-04-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesalesreport',
            options={'verbose_name': 'Отчет о продажах магазина', 'verbose_name_plural': 'Отчеты о продажах магазина'},
        ),
    ]
