# Generated by Django 5.0.2 on 2025-03-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shop_remove_product_gearbox_remove_product_recommend_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vk',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='products.shop', verbose_name='Магазин'),
        ),
    ]
