# Generated by Django 5.0.2 on 2025-03-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Название в URL')),
                ('type', models.CharField(choices=[('self-employed', 'самозанятый'), ('individual_entrepreneur', 'Индивидуальный предприниматель'), ('legal_person', 'юрлицо')], default='self-employed', max_length=150, verbose_name='Тип')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='shops_docs/passports/', verbose_name='паспорт')),
                ('INN', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('OGRNIP', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРНИП')),
                ('OGRN', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('verified', models.BooleanField(default=False, verbose_name='Верифицированный')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recommend',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Верифицированный'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.shop', verbose_name='Магазин'),
        ),
    ]
