# Generated by Django 5.0.2 on 2025-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shop_remove_product_gearbox_remove_product_recommend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
