# Generated by Django 5.0.2 on 2025-04-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_height',
            field=models.FloatField(default=1, max_length=50, verbose_name='Высота при доставке в см'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_length',
            field=models.FloatField(default=1, max_length=50, verbose_name='Длина при доставке в см'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight',
            field=models.FloatField(default=1, max_length=50, verbose_name='Вес при доставке в кг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_width',
            field=models.FloatField(default=1, max_length=50, verbose_name='Ширина при доставке в см'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_city',
            field=models.CharField(default='Москва', max_length=250, verbose_name='Город Склада'),
            preserve_default=False,
        ),
    ]
