# Generated by Django 5.0.2 on 2025-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatibility',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Совместимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='/product_img/default_product_detail_img.png', help_text='Минимальный рекомендуемый размер - 536x639', upload_to='product_img/', verbose_name='Изображение 1 для страницы продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='Минимальный рекомендуемый размер - 536x639', null=True, upload_to='product_img/', verbose_name='Изображение 2 для страницы продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='Минимальный рекомендуемый размер - 536x639', null=True, upload_to='product_img/', verbose_name='Изображение 3 для страницы продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, help_text='Минимальный рекомендуемый размер - 536x639', null=True, upload_to='product_img/', verbose_name='Изображение 4 для страницы продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, help_text='Минимальный рекомендуемый размер - 1140x760', null=True, upload_to='product_img/', verbose_name='Изображение для описания на странице продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(default='/product_img/default_products_list_img.png', help_text='Минимальный рекомендуемый размер - 433x516', upload_to='product_img/', verbose_name='Изображение для показа в списках'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_to_a_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип крепления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='principle_of_operation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Принцип действия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thread_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип резьбы'),
        ),
    ]
