# Generated by Django 5.0.2 on 2025-04-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_compatibility_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
