# Generated by Django 5.0.2 on 2025-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatibility',
            field=models.CharField(blank=True, help_text='Рекомендуется для прикладов, магазинов, триггеров, цевья, стволиков', max_length=250, null=True, verbose_name='Совместимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.FloatField(blank=True, help_text='Рекомендуется для стволиков', null=True, verbose_name='Диаметр в мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imitation_of_a_shot',
            field=models.BooleanField(blank=True, help_text='Рекомендуется для трассерных насадок', null=True, verbose_name='Имитация выстрела'),
        ),
        migrations.AlterField(
            model_name='product',
            name='laser_sight',
            field=models.BooleanField(blank=True, help_text='Рекомендуется для фонарей', null=True, verbose_name='С ЛЦУ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, help_text='Рекомендуется для стволиков', null=True, verbose_name='Длина в мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mounting_type',
            field=models.CharField(blank=True, help_text='Рекомендуется для тактических рукояток', max_length=250, null=True, verbose_name='Тип крепления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='principle_of_operation',
            field=models.CharField(blank=True, help_text='Рекомендуется для автоматов, винтовок и пистолетов', max_length=250, null=True, verbose_name='Принцип действия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='Рекомендуется для ДТК, глушителей, прикладов, фонарей, масок, очков, шаров, экипировки, hop-up, стволиков, прикладов', max_length=250, null=True, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thread_type',
            field=models.CharField(blank=True, help_text='Рекомендуется для ДТК, глушителей, трассерных насадок', max_length=250, null=True, verbose_name='Тип резьбы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='Рекомендуется для шаров', null=True, verbose_name='Вес в гр.'),
        ),
    ]
