# Generated by Django 5.0.2 on 2025-04-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_compatibility_alter_product_diameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
