# Generated by Django 5.0.2 on 2025-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_options_review_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='passport',
        ),
        migrations.AddField(
            model_name='shop',
            name='BIC',
            field=models.CharField(default=123456789, max_length=9, verbose_name='БИК'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default=1, help_text='Для всех. Страна, область, город, индекс, улица, дом', max_length=250, verbose_name='Адрес регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='payment_account',
            field=models.CharField(default=1, help_text='Только банка РФ', max_length=20, verbose_name='Расчётный счёт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='INN',
            field=models.CharField(default=1, help_text='Для всех', max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='OGRN',
            field=models.CharField(blank=True, help_text='Для юрлиц', max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='OGRNIP',
            field=models.CharField(blank=True, help_text='Для ИП', max_length=15, null=True, verbose_name='ОГРНИП'),
        ),
    ]
